[package]
name = "aoc-03a"
version = "0.1.0"
authors = ["Ryan B. Harvey <ryan.b.harvey@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
transpose = "0.2.1"
